### PR TITLE
Rpi wsl

### PR DESCRIPTION
**Pull request by karu2003**
build in WSL Ubuntu. Added target reTerminal. The screen rotation does not work and there is no touchscreen.

### CODE REVIEW

**Comment by raphaelscholle** [comment]
Thanks for the pull request, but since it breaks some fundamental things, I will not be able to merge it.
here is a list of the problems:

[1.](https://github.com/OpenHD/OpenHD-ImageBuilder/pull/243/files#diff-a5d0e9300b40df90001805aaf7a9022bf05f7e86681130d5bb8be7fbcb687f02) it's completely unnecessary to build an additional image for the support of one display, which is not commonly used [](url)
2. Updating the base image needs testing, and since we don't gain anything right now I'll hold the update a little bit until I've checked compatibility 
[3.](https://github.com/OpenHD/OpenHD-ImageBuilder/pull/243/files#diff-1376efd42ddaab8828e3bb8750755f7e410804abeb71fb0800d7c08059d0ec6c) you install overlays, which are not compiled within our custom kernel, this will affect stability and produce unexpected behaviour, if you need an overlay for that monitor you can add the compilation of said overlay into our custom kernel [here ](https://github.com/OpenHD/OpenHD-KernelBuilder).
Even when compiling the dto's inside the image builder it will be compiled with the kernel of the host-machine, overlays must be compiled with the right kernel-headers or better directly inside the kernel-builder to be compatible
4. we manage our config.txt and the overlyas inside dynamically by openhd, forcing overlays is a bad practice in OpenHD-Evo´, experienced users can do that in their own system, but it shall not be done within the builder

**Comment by raphaelscholle** [comment]
To get reterminal supported you just need to get the sourcecode of the device tree overlays and try to patch it into our kernel builder (keep in mind that this needs to be fully manitainable)
then you can add the overlay before the #Dynamic config-line
but do not try to set fkms/kms/legacy, this will stop openhd from working.

Everything that works in stock raspbian (without X) will work in openhd, touch should all be handled by the device itself.
If only newer raspbian versions are supported I can check updating, but that needs to be verified prior.

**Comment by karu2003** [comment]
I managed to rotate the screen. by adding settings to cmd. video=DSI-1:720x1280@60,rotate=270. The screen in Onep.HD remained unchanged. Not correctly rotated. I'll wait for you to make a new release. 2.2.x. Release 2.0.12 does not work in Boster on reTerminal.  Do you have recipes for how to build a project without building an image?

**Comment by raphaelscholle** [comment]
we can discuss this in telegram, I'll close this issue now

**Pull request closed without merging**
